### ISSUE TITLE
xGroupResource: Creates error on forcing members for builtin Administrators group

### ISSUE THREAD

**Issue by tmeckel** [dsccommunity/xPSDesiredStateConfiguration#467]
#### Details of the scenario you tried and the problem that is occurring

For details refer to the same issue at PSDscResources https://github.com/PowerShell/PSDscResources/issues/87. 

as seen here https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/9fd047b90f3d74c4a83e0ae0011da1af5b916bbd/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L2439 the code for xGroupResource suffers from the same problem as the GroupResource in PSDscResources.

#### Verbose logs showing the problem

ref to https://github.com/PowerShell/PSDscResources/issues/87.

#### Suggested solution to the issue

porting the fix from PR https://github.com/PowerShell/PSDscResources/pull/118 in PSDscResources 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Group GroupExample
{
    Ensure = "Present"
    GroupName = "Administrators"
    Members = @( ".\Administrator", "<Domain>\<SamAccountName>")
}
```
or
```powershell
Group GroupExample
{
    Ensure = "Present"
    GroupName = "Administrators"
    Members = @( "<Domain>\<SamAccountName>")
}
```

**Comment by PlagueHO** [comment]
Thanks @tmeckel - we will want to back port that fix into here as you say. Once I've started getting the other backport PR's through then I'll get onto this (unless someone else gets there first).
