### ISSUE TITLE
Increase Performance of Test-IsNanoServer

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/xPSDesiredStateConfiguration#652]
The cmdlet `Test-IsNanoServer` is used by many of the resources. This cmdlet uses `Get-ComputerInfo` to determine if the machine is Nano server:
```powershell
function Test-IsNanoServer
{
    [OutputType([System.Boolean])]
    [CmdletBinding()]
    param ()

    $isNanoServer = $false

    if (Test-CommandExists -Name 'Get-ComputerInfo')
    {
        $computerInfo = Get-ComputerInfo

        $computerIsServer = 'Server' -ieq $computerInfo.OsProductType

        if ($computerIsServer)
        {
            $isNanoServer = 'NanoServer' -ieq $computerInfo.OsServerLevel
        }
    }

    return $isNanoServer
}
```

However, `Get-ComputerInfo` is very slow, taking over 2 seconds on average to execute.

This causes the resources to run slow and increases overall test time significantly.

We should find a better way to detect if a machine is Nano Server.

**Comment by PlagueHO** [comment]
One possible way of increasing performance is to instead use a CIM command to pull the `Win32_OperatingSystem` class (https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-operatingsystem) and use the OperatingSystemSKU property:

```powershell
$productDatacenterNanoServer = 143
$productStandardNanoServer = 144

function Test-IsNanoServer
{
    [OutputType([System.Boolean])]
    [CmdletBinding()]
    param ()

    $operatingSystemSKU = (Get-CimInstance -ClassName Win32_OperatingSystem).OperatingSystemSKU

    return ($operatingSystemSKU -in ($productDatacenterNanoServer,$productStandardNanoServer))
}
```

Is there anyone who knows a reason why this would not be a viable alternative? @gaelcolas , @johlju

**Comment by johlju** [comment]
If the class exist in a Nano server then I don't see an issue using it.

**Comment by HansOMartinsen** [comment]
The class exists on Nanaoserver. Ref: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt588480(v=vs.85)

Any reason not to go ahead and implement this as in "Add Test-IsNanoServer dsccommunity/DscResource.Common#9"?

**Comment by PlagueHO** [comment]
No reason at all :) Please go ahead @HansOMartinsen !

**Comment by PlagueHO** [comment]
Implementing #685 will resolve this issue. I'll be planning this over the next week.
