### ISSUE TITLE
link to sample configurations under does not exist any more

### ISSUE THREAD

**Issue by bingbing8** [dsccommunity/xPSDesiredStateConfiguration#659]
links to sample configurations under blob does not exist any more. For example: [A Pull Server default configuration](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/master/Examples/Sample_xDscWebServiceRegistration_Win2k12and2k12R2.ps1)
Please fix it

**Comment by PlagueHO** [comment]
Thanks for raising this @bingbing8. This will have happened during migration to the new repo layout. I'll get this corrected ASAP.
