### ISSUE TITLE
xPSDesiredStateConfiguration version 9.0.0 is no longer exporting commands

### ISSUE THREAD

**Issue by kscelfo** [dsccommunity/xPSDesiredStateConfiguration#673]
#### Details of the scenario you tried and the problem that is occurring
After updating to xPSDesiredStateConfiguration 9.0.0, I can no longer utilize the Publish-ModuleToPullServer command.

#### Verbose logs showing the problem

Module Type | Version | Name | Exported Commands
-------------- | -------- | ------ | -----------------------
Script | 9.0.0 | xPSDesiredStateConfiguration
Script | 8.10.0.0 | xPSDesiredStateConfiguration | {Publish-ModuleToPullServer, Publish-DSCModuleAndMof, Publ...

#### Suggested solution to the issue
Please export those functions. They are immensely helpful in our CI/CD process.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
n/a, issue presents on the pull server.

#### The operating system the target node is running
Name | Value
------- | ------
OsName | Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU | DatacenterServerEdition
OsArchitecture | 64-bit
WindowsBuildLabEx | 14393.3442.amd64fre.rs1_release.191219-1727
OsLanguage | en-US
OsMuiLanguages | {en-US}

#### Version and build of PowerShell the target node is running
Name | Value
------- | ------
PSVersion | 5.1.14393.3383
PSEdition | Desktop
PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0...}
BuildVersion | 10.0.14393.3383
CLRVersion | 4.0.30319.42000
WSManStackVersion | 3.0
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.1

#### Version of the DSC module that was used
9.0.0

**Comment by PlagueHO** [comment]
Hi @kscelfo - thanks for raising this. This must have happened when I migrated the module to the new CI/CD structure. I'll correct this ASAP and get a new release out.
