### ISSUE TITLE
xRemoteFile: Fix inconsistencies in messages for en-us

### ISSUE THREAD

**Issue by BITespresso** [dsccommunity/xPSDesiredStateConfiguration#716]
#### Details of the scenario you tried and the problem that is occurring

The message string defined in `DSC_xRemoteFile.strings.psd1` have some inconsistencies in quoting and case:

Examples:

`Specified URI is not valid: "{0}". Only http, https or file paths are accepted.`
(uses double quotes and uppercase URI)

vs

`No cache found for DestinationPath '{0}' and Uri '{1}' CacheKey '{2}'.`
(uses single quotes and Uri instead of URI)

#### Suggested solution to the issue

Fix message strings

**Comment by BITespresso** [comment]
I'd like to resolve this issue.

**Comment by PlagueHO** [comment]
Hi @BITespresso - your help is greatly appreciated. Please feel free to submit a pull request for this and I'll get onto review this weekend.

**Comment by BITespresso** [comment]
The pull request should already be here and is complete from my side. Looking forward to your review.
