### ISSUE TITLE
xPackage: With Azure KeyVault, Is it possible to pass a secure parameter to the Arguments value? #266

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [dsccommunity/xPSDesiredStateConfiguration#738]
Its been 5 years since a similar question was asked: [Issue 266](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/266)

Using Azure KeyVault, I have 2 Secrets (username, password) I need to pass into an xPackage argument.

How can I pass the parameters as plaintext into the 'arguments' section of an xpackage?

I tried using the Mashall class as an additional parameter that gets derived, but haven't been successful yet:
[System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($KVPasswordsecureString))

Currently it is set like this more or less:
.json

```
{
  "type": "extensions",
  "name": "DSC",
  "apiVersion": "2020-06-01",

"properties:"
  "typehandler" "2.77"
   "configurationArguments":{
          "KVUserstring": "[parameters('KVUserstring')]",
}

  "protectedSettings": {
                        "configurationArguments": {
                            "KVPasswordsecureString": "[parameters('KVPasswordsecureString')]",
  }


```
.ps1
```
param
(
    [string] $KVUserstring,
    [securestring] $KVPasswordsecureString,
)

xPackage app
{
...
Arguments = "ADMIN_USER=$KVUserstring ADMIN_USER_PASSWORD=$KVPasswordsecureString"
}
```

Azure automation is not an available choice for my environment.

**Comment by PlagueHO** [comment]
Hi @CHDAFNI-MSFT,

There are a couple of things to consider here:

1. When the MOF above is compiled, even if you pass the parameter in as a SecureString, the value that is set in the Arguments parameter in the resulting MOF will contain the plain text password - you would need to ensure you're using MOF encryption to deal with this: https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/secureMOF?view=powershell-7.1
2. You would need to convert the SecureString parameter into a plain text string when you insert it into the Arguments parameter - e.g. 
```powershell
param
(
    [string] $KVUserstring,
    [securestring] $KVPasswordsecureString,
)

xPackage app
{
...
Arguments = "ADMIN_USER=$KVUserstring ADMIN_USER_PASSWORD=$(Convert-FromSecureString -SecureString $KVPasswordsecureString -AsPlainText)"
}
```

Note: The above method uses PS 7 syntax for converting from a SecureString - IIRC PS 5.1 requires a different method.

Does that line up with your use case?

You could also consider not passing these parameters into the DSC config at all - instead, use the Azure Instance Metadata Service with an Azure Managed Identity for the VM. Then at the start of the DSC config, pull the Username & Password from the AKV using the Managed Identity. I can go into a bit more detail on this approach if required. It will still require converting the SecureString to a string though in the Arguments property.

**Comment by CHDAFNI-MSFT** [comment]
> Note: The above method uses PS 7 syntax for converting from a SecureString - IIRC PS 5.1 requires a different method.
> 
> Does that line up with your use case?
> 
> You could also consider not passing these parameters into the DSC config at all - instead, use the Azure Instance Metadata Service with an Azure Managed Identity for the VM. Then at the start of the DSC config, pull the Username & Password from the AKV using the Managed Identity. I can go into a bit more detail on this approach if required. It will still require converting the SecureString to a string though in the Arguments property.

Thanks for responding @PlagueHO 
It would be with 5.1.. The Azure DSC extension should take care of encrypting the MOF on the target VM. Unfortunately, managed identities are not possible since they aren't yet available in Azure Stack Hub.

I understand what you're stating which is regardless of how it is passed to the DSC Configuration script (string vs securestring / (assuming settings vs protectedsettings), it'll be in whatever format the DSC Configuration parameter is configured for. I'll give it another shot. Thanks for the background info.
