### ISSUE TITLE
Version is incorrect in PDS1

### ISSUE THREAD

**Issue by RobBiddle** [dsccommunity/xPSDesiredStateConfiguration#741]
Version shows '0.0.1' instead of '9.1.0.0'
(https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/9940d6bd5b839773ffc0427047598ef9cb5693f0/source/xPSDesiredStateConfiguration.psd1#L6)

**Comment by PlagueHO** [comment]
Hi @RobBiddle - This is by design. The moduleVersion is inserted automatically during the build process. Would it help to add a comment to the PSD1 indicating that is automatically generated?

**Comment by RobBiddle** [comment]
Ahh that makes sense, I wasn't installing from the repository. I just grabbed the source files, which fail to import without modifying the PSD1.

**Comment by RobBiddle** [comment]
FYI The package from the PS Gallery shows as '9.1.0' which also needs to renamed to be compatible with requirements for DSC modules required naming pattern: https://docs.microsoft.com/en-us/powershell/dsc/pull-server/pullserver?view=dsc-1.1#dsc-resource-module-package-format

**Comment by PlagueHO** [comment]
Ah right - yes - that will happen. If you want to do that, you can, but just run the sampler build process first and it will produce a local copy for you (although there are a few pre-req's).
